### ISSUE TITLE
issues with repeater implementation

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#527]
### Tasks
- [ ] timeout needs to be implemented
- [ ] add tests for api
- [ ] add support for multi-action calling
- [ ] add integration test for repeater
- [ ] move API business logic out of the rest_api service and into the repeater component
