### ISSUE TITLE
DataPackages endpoint bugs

### ISSUE THREAD

**Issue by naman108** [FreeTAKTeam/FreeTakServer#657]
With the changes to the enterprise sync component, some of the existing data package endpoints are exhibiting unexpected behavior.

```[tasklist]
### Tasks
- [x] Get Data Packages returns all enterprise sync entries
- [x] Delete Data Packages is failing
- [x] Add Datapackage From UI is failing
```

**Comment by brothercorvo** [comment]
we can close this @naman108 ?

**Comment by naman108** [comment]
Not until we test and pull
